name: core_app
description: "A simplest Clean Architecture Flutter Apps"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^10.1.2
  cached_network_image: ^3.4.1

  cupertino_icons: ^1.0.8
  dio: ^5.7.0

  envied: ^1.1.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.16
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  latlong2: ^0.9.0
  logging: ^1.3.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  shared_preferences: ^2.3.5
  skeletonizer: ^2.1.0+1
  chucker_flutter: ^1.6.2


dev_dependencies:
  auto_route_generator: ^10.2.4
  build_runner: ^2.4.14
  envied_generator: ^1.1.1
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  retrofit_generator: ^10.0.5

flutter_gen:
  output: lib/src/shared/assets/
  line_length: 80
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/markdowns/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Syne-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Syne-Bold.ttf
          weight: 700
        - asset: assets/fonts/Syne-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Syne-Medium.ttf
          weight: 500
        - asset: assets/fonts/Syne-Regular.ttf
          weight: 400
